version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: mern-docker-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - frontend
    networks:
      - mern-docker

  frontend:
    build: ./frontend
    container_name: mern-docker-frontend
    command: serve -s build -l 3000
    restart: unless-stopped
    networks:
      - mern-docker

  api:
    build: ./api
    container_name: mern-docker-api
    command: npm run start
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - HOST=http://merndocker.com
      - MONGO_URL=mongodb://api_db:27017/api
      - AUTH_API_URL=http://auth:3002/api
    depends_on:
      - api_db
    networks:
      - mern-docker

  auth:
    build: ./auth
    container_name: mern-docker-auth
    command: npm run start
    restart: unless-stopped
    ports:
        - "3002:3002"
    environment:
      - PORT=3002
      - MONGO_URL=mongodb://auth_db:27017/auth
      - API_URL=http://api:3001/api
    depends_on:
      - auth_db
    networks:
      - mern-docker

  api_db:
    container_name: mern-docker-api-db
    image: mongo:latest
    volumes:
      - mongodb_api:/data/db
    networks:
      - mern-docker

  auth_db:
    container_name: mern-docker-auth-db
    image: mongo:latest
    volumes:
      - mongodb_auth:/data/db
    networks:
      - mern-docker

volumes:
  mongodb_api:
  mongodb_auth:

networks: 
  mern-docker:
    driver: bridge
  