version: '3'

services:
  api:
    build: ./api # to build container
    command: npm run start # command for starting container
    restart: unless-stopped # to restart app if its stopped
    ports: # our port : app port
      - "3000:3000"
    environment:
      - PORT=3000
      - HOST=http://dockerizing.com
      - MONGO_URL=mongodb://api_db:27017/api
    depends_on:
      - api_db

  api_db:
    image: mongo:latest
