version: '3'

services:
  frontend: 
    build: ./frontend
    container_name: mern-docker-frontend
    command: serve -s build -l 3000
    restart: unless-stopped
    ports:
      - "3000:3000"

  api:
    build: ./api # to build container
    container_name: mern-docker-api
    command: npm run start # command for starting container
    restart: unless-stopped # to restart app if its stopped
    ports: # our port : app port
      - "3001:3001"
    environment:
      - PORT=3001
      - HOST=http://merndocker.com
      - MONGO_URL=mongodb://api_db:27017/api
    depends_on:
      - api_db

  auth:
    build: ./auth
    container_name: mern-docker-auth
    command: npm run start
    restart: unless-stopped
    ports:
        - "3002:3002"
    environment:
      - PORT=3002
      - MONGO_URL=mongodb://auth_db:27017/auth
    depends_on:
      - auth_db

  api_db:
    container_name: mern-docker-api-db
    image: mongo:latest
    volumes:
      - mongodb_api:/data/db

  auth_db:
    container_name: mern-docker-auth-db
    image: mongo:latest
    volumes:
      - mongodb_auth:/data/db

volumes:
  mongodb_api:
  mongodb_auth:
